### ISSUE TITLE
Raid/Dungeon Problems, again

### ISSUE THREAD

**Issue by norsehealer** [tyra314/ElvUI_SmartQuestTracker#1]
I'm in Pandaria, at The Jade Forest, doing the Cloud Serpent quest and [110r] Into the Nightmare: Fall of Cenarius is popping up.

It's been pretty good lately, btw.

**Comment by tyra314** [comment]
I'll look into it. It probably needs more special cases in the detection logic 😢

**Comment by tyra314** [comment]
I wasn't able to reproduce this issue. For one, I don't have the quest in question. I tried it with "The Emerald Nightmare: In Nightmares" but it didn't happen. And also I'm exalted with cloud serpents, so I probably have diferent quests there. Does it happen every time for you? If not, it's probably a random glitch, those happen from time to time still. 😭

**Comment by tyra314** [comment]
With the new version for BfA, I just hope this won't happen anymore. I'm closing this now, feel free to reopen, if it still happens.
