### ISSUE TITLE
Not saving settings.

### ISSUE THREAD

**Issue by fireymerlin** [tyra314/ElvUI_SmartQuestTracker#2]
The addon is not saving settings between logons.
The ".toc" file does not have an entry in it for "## SavedVariables:", etc.

**Comment by tyra314** [comment]
I guess, you're talking about the non-ElvUI version, right?

**Comment by tyra314** [comment]
Fixed in the new repo:
https://github.com/tyra314/SmartQuestTracker/commit/94edc7cb9d603fda6c6d259d013ec1f206bd53bd

Will be included in v2.0.10
