### ISSUE TITLE
Rewrite using BFA api

### ISSUE THREAD

**Issue by Langmans** [tyra314/ElvUI_SmartQuestTracker#3]
As it no longer works ;)

**Comment by tyra314** [comment]
Yes, I'm aware of it. However, I focused on the standalone version as it's easier to port without the ElvUI dependency. So, if you can't live without a smarter quest tracker, you can use that one: https://wow.curseforge.com/projects/smartquesttracker

**Comment by tyra314** [comment]
Done. The new version is under review.

https://wow.curseforge.com/projects/elvui_smartquesttracker/files/2601946
