### ISSUE TITLE
something is missing?

### ISSUE THREAD

**Issue by einmiau** [tyra314/ElvUI_SmartQuestTracker#4]
i have elvui installed and downloaded your addon from the twitch app, so i thought i wouldn't need those other pieces. however ingame the addon can't be activated because it says that there is something missing. i installed scorpio and ploop manually after that, still the same message. what am i doing wrong?

**Comment by tyra314** [comment]
I have no freaking idea what ploop and scorpio are; you're sure whatever message you're seeing comes from my addon? My addon doesn't have any dependencies other than ElvUI.
