### ISSUE TITLE
Get this Error after Prepatch and ElvUi 12

### ISSUE THREAD

**Issue by TaZzDE** [tyra314/ElvUI_SmartQuestTracker#5]
1x ...\ElvUI_SmartQuestTracker\ElvUI_SmartQuestTracker-v3.1.6.lua:128: attempt to call global 'GetNumQuestLogEntries' (a nil value)
[string "@ElvUI_SmartQuestTracker\ElvUI_SmartQuestTracker-v3.1.6.lua"]:128: in function <...\ElvUI_SmartQuestTracker\ElvUI_SmartQuestTracker.lua:127>
[string "@ElvUI_SmartQuestTracker\ElvUI_SmartQuestTracker-v3.1.6.lua"]:224: in function `Update'
[string "@ElvUI_SmartQuestTracker\ElvUI_SmartQuestTracker-v3.1.6.lua"]:562: in function <...\ElvUI_SmartQuestTracker\ElvUI_SmartQuestTracker.lua:549>
[string "=[C]"]: ?
[string "@ElvUI\Core\Core.lua"]:1326: in function `CallLoadFunc'
[string "@ElvUI\Core\Core.lua"]:1341: in function `CallLoadedModule'
[string "@ElvUI\Core\Core.lua"]:1367: in function `InitializeModules'
[string "@ElvUI\Core\Core.lua"]:1459: in function <ElvUI\Core\Core.lua:1427>
[string "=[C]"]: in function `Initialize'
[string "@ElvUI\init.lua"]:153: in function <ElvUI\init.lua:152>
[string "=[C]"]: ?
[string "@ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <...s\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <...s\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:615>

**Comment by tyra314** [comment]
I haven't updated the ElvUI version of SmartQuestTracker to SL, yet. I'm not sure if and when I will, because I don't use ElvUI anymore. **However**, you can just switch to the generic version of my addon, which has been updated: https://www.curseforge.com/wow/addons/smartquesttracker

**Comment by TaZzDE** [comment]
> I haven't updated the ElvUI version of SmartQuestTracker to SL, yet. I'm not sure if and when I will, because I don't use ElvUI anymore. **However**, you can just switch to the generic version of my addon, which has been updated: https://www.curseforge.com/wow/addons/smartquesttracker

ok Thx I use the generic Version
