### ISSUE TITLE
ElvUI_SmartQuestTracker.lua:128: attempt to call global 'GetNumQuestLogEntries' (a nil value)

### ISSUE THREAD

**Issue by xan2622** [tyra314/ElvUI_SmartQuestTracker#6]
🔵 **Describe the bug:**
I installed **ElvUI_SmartQuestTracker** thanks to [Ajour](https://www.getajour.com/) and right after logging in the game, the following error appeared: `ElvUI_SmartQuestTracker.lua:128: attempt to call global 'GetNumQuestLogEntries' (a nil value)`

🔵 **Steps to reproduce the behavior:**
1. Install the ElvUI_SmartQuestTracker addon 
2. Run the game
3. See error

🔵 **The error:**

```
Message: ...\ElvUI_SmartQuestTracker\ElvUI_SmartQuestTracker.lua:128: attempt to call global 'GetNumQuestLogEntries' (a nil value)
Time: Mon Aug  2 07:21:56 2021
Count: 1
Stack: ...\ElvUI_SmartQuestTracker\ElvUI_SmartQuestTracker.lua:128: attempt to call global 'GetNumQuestLogEntries' (a nil value)
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:761: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\ElvUI_SmartQuestTracker\ElvUI_SmartQuestTracker.lua"]:128: in function <...\ElvUI_SmartQuestTracker\ElvUI_SmartQuestTracker.lua:127>
[string "@Interface\AddOns\ElvUI_SmartQuestTracker\ElvUI_SmartQuestTracker.lua"]:224: in function `Update'
[string "@Interface\AddOns\ElvUI_SmartQuestTracker\ElvUI_SmartQuestTracker.lua"]:562: in function <...\ElvUI_SmartQuestTracker\ElvUI_SmartQuestTracker.lua:549>
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI\Core\Core.lua"]:1752: in function `CallLoadFunc'
[string "@Interface\AddOns\ElvUI\Core\Core.lua"]:1767: in function `CallLoadedModule'
[string "@Interface\AddOns\ElvUI\Core\Core.lua"]:1793: in function `InitializeModules'
[string "@Interface\AddOns\ElvUI\Core\Core.lua"]:1897: in function <Interface\AddOns\ElvUI\Core\Core.lua:1865>
[string "=[C]"]: in function `Initialize'
[string "@Interface\AddOns\ElvUI\init.lua"]:163: in function <Interface\AddOns\ElvUI\init.lua:162>
[string "=[C]"]: ?
[string "@Interface\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:630: in function <...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: <none>
```

🔵 **Screenshot:**

<img src="https://user-images.githubusercontent.com/1732773/127808570-eba2f2ce-2a9c-4ecc-9dec-1cded76a0528.jpg" width="50%" height="50%">

🔵 **Desktop:**
OS: Windows 10 64bits pro
Hardware: nvidia GTX 1070 8GB - driver: 471.11

🔵 **Game Version:**
World of Warcraft Shadowlands Retail version 9.1.0.39617  (French language)

🔵 **Addon Version:**
3.1.6

🔵 **ElvUI Addon Version:**
12.37

**Comment by RyadaProductions** [comment]
Hey Xan, I have seen the same issue after installing the addon earlier today. I am currently trying to port the addon to the newest API version from Blizzard itself. The API changed when they released Shadowlands and since the addon hasn't been updated since then it started to break. I'm unsure if the original developer of the addon want's a PR as it seems he hasn't responded nor updated the repository for a while now.

**Comment by tyra314** [comment]
You can also use the standalone version: https://www.curseforge.com/wow/addons/smartquesttracker
I believe it should work with shadowlands.

**Comment by RyadaProductions** [comment]
It seems like the standalone works with Shadowlands but it doesn't seem to untrack or update the questlist properly when using Elvui. As an example I'm seeing quests from Silithus while in Oribos, so I figured that the Elvui one specifically should work after updating it since it's specifically for Elvui. (at least from my assumption)
